# make sure that the environment variables ARCH and CROSS_COMPILE
# are set for your architecture and cross compiler.
# And that KDIR points to the kernel to build against.
#
# e.g.:
# export ARCH=arm
# export CROSS_COMPILE=arm-linux-gnueabihf-
# export KDIR=../linux

MODULE_NAME := tas2557_dlkm

ccflags-y += -I$(srctree)/$(src)/inc
ccflags-y += -Werror

obj-$(CONFIG_SND_SOC_TAS2557_STEREO) := $(MODULE_NAME).o

$(MODULE_NAME)-objs += tas2557-core.o
$(MODULE_NAME)-objs += tas2557-regmap.o
$(MODULE_NAME)-objs += tas2557-codec.o
$(MODULE_NAME)-objs += tas2557-misc.o
$(MODULE_NAME)-objs += tiload.o

# Disable enum conversion warning
subdir-ccflags-y := $(call cc-disable-warning, enum-conversion)

ifeq ($(CONFIG_SND_SOC_GCOV), y)
GCOV_PROFILE := y
endif
